### ISSUE TITLE
Navigation Bar Component

### ISSUE THREAD

**Issue by conroyr41** [conroyr41/Workout-Tracker#2]
We need a navigation bar component that will be used throughout the app.

The navigation bar should look just like the prototype:

<img src="https://user-images.githubusercontent.com/72236249/221437407-94014d09-379c-4247-b319-92219b7a59ef.png" width="300">

**Comment by christina8711** [comment]
I got this one! Thanks, Conroy

**Comment by conroyr41** [comment]
Issue resolved.
